# Importing Neccessary libraries

In [2]:
import numpy as np 
import pandas as pd

# Importing and loading the data

In [4]:
data = pd.read_csv(r'Downloads\stockdata.csv')

In [27]:
data

,DATE,OPEN,HIGH,LOW,PREV. CLOSE,CLOSE,TOTAL TRADED QUANTITY,TURNOVER,NO. OF TRADES
0,03-Jun-2020,100.00,101.45,97.40,96.50,98.75,90600115,"9,073,798,058.20",296653
1,01-Jun-2020,88.90,91.20,88.00,87.00,89.55,71081216,"6,399,189,823.50",207071
2,29-May-2020,85.55,87.50,84.65,87.00,87.00,80819025,"6,937,284,941.50",210894
3,28-May-2020,86.00,88.15,84.55,84.55,87.00,96183461,"8,317,754,409.30",254053
4,27-May-2020,84.10,86.00,84.00,83.10,84.55,57958863,"4,923,419,055.20",144270
5,26-May-2020,83.90,85.70,82.60,82.80,83.10,38018351,"3,197,222,250.60",116618
6,22-May-2020,83.40,83.90,82.00,84.10,82.80,29252936,"2,422,831,924.30",96301
7,21-May-2020,83.10,85.20,82.90,83.45,84.10,37290910,"3,142,196,365.85",119854
8,20-May-2020,81.25,84.40,80.70,81.80,83.45,36351616,"3,015,914,660.45",116445
9,19-May-2020,82.50,85.65,81.50,80.65,81.80,65379359,"5,469,427,810.40",194462
10,18-May-2020,84.50,84.50,79.60,84.35,80.65,44221575,"3,588,181,738.75",163410
11,15-May-2020,84.70,85.35,82.80,83.80,84.35,38594210,"3,238,366,014.30",124113
12,14-May-2020,83.95,85.30,82.55,87.20,83.80,46341703,"3,896,726,738.70",173963
13,13-May-2020,92.50,92.50,86.25,86.20,87.20,68086246,"6,036,002,630.40",237994
14,12-May-2020,85.95,87.70,83.50,86.10,86.20,77552355,"6,593,767,114.50",245351
15,11-May-2020,81.45,90.65,81.40,81.05,86.10,152592033,"13,267,842,790.60",470511
16,08-May-2020,84.50,84.95,80.55,82.50,81.05,35363226,"2,916,175,375.35",135944
17,07-May-2020,82.90,84.65,82.10,83.20,82.50,31160671,"2,595,015,270.60",119183
18,06-May-2020,81.55,83.95,80.35,80.90,83.20,53739428,"4,435,743,139.40",166733
19,05-May-2020,86.00,86.80,80.40,83.90,80.90,57123018,"4,816,372,491.95",194041
20,04-May-2020,87.00,87.20,81.50,93.25,83.90,91167307,"7,666,846,446.55",327945
21,30-Apr-2020,85.95,93.75,85.95,78.15,93.25,170645234,"15,233,902,188.60",519684
22,29-Apr-2020,77.45,79.30,76.55,76.95,78.15,40785025,"3,184,101,597.95",133880
23,28-Apr-2020,75.65,78.20,75.20,75.25,76.95,34825466,"2,675,737,156.65",107365
24,27-Apr-2020,75.90,76.20,74.80,74.20,75.25,27835405,"2,098,869,538.60",93555
25,24-Apr-2020,75.00,76.90,74.00,75.65,74.20,40054235,"3,024,343,540.85",129250
26,23-Apr-2020,76.75,78.65,75.40,75.90,75.65,50372620,"3,875,896,447.15",161989
27,22-Apr-2020,74.45,76.55,72.55,74.65,75.90,56529909,"4,202,665,230.00",183754
28,21-Apr-2020,78.00,78.00,74.00,80.45,74.65,58249560,"4,396,212,525.25",223568
29,20-Apr-2020,76.85,83.40,75.50,76.85,80.45,125427754,"10,152,471,072.75",400016
...,...,...,...,...,...,...,...,...,...
338,14-Jan-2019,180.30,198.30,177.45,180.30,182.40,18935120,"3,422,007,613.90",94255
339,11-Jan-2019,186.55,187.75,179.40,185.75,180.30,25902974,"4,727,945,471.15",122548
340,10-Jan-2019,183.65,186.85,183.55,183.05,185.75,16961888,"3,150,521,337.85",96659
341,09-Jan-2019,181.50,183.60,180.20,179.95,183.05,17468948,"3,180,237,350.20",114177
342,08-Jan-2019,176.10,180.50,176.10,175.35,179.95,20128985,"3,603,338,781.30",116893
343,07-Jan-2019,173.20,178.20,173.20,170.95,175.35,21438351,"3,778,953,045.30",136086
344,04-Jan-2019,169.00,171.95,168.50,166.05,170.95,17650435,"3,008,777,564.85",103949
345,03-Jan-2019,169.00,170.15,165.10,168.55,166.05,9321842,"1,564,267,952.55",71994
346,02-Jan-2019,170.60,171.75,168.00,173.45,168.55,13410104,"2,277,669,120.50",77641
347,01-Jan-2019,173.50,174.20,171.30,172.70,173.45,6715543,"1,159,866,971.20",42618
348,31-Dec-2018,172.45,173.90,171.75,170.85,172.70,8511388,"1,470,736,017.50",53654
349,28-Dec-2018,169.40,172.20,169.15,168.25,170.85,8669584,"1,483,786,775.25",52303
350,27-Dec-2018,172.75,173.40,167.70,170.90,168.25,15231581,"2,587,331,015.45",78643
351,26-Dec-2018,171.45,172.20,167.60,172.50,170.90,12044191,"2,047,301,453.05",73360
352,24-Dec-2018,176.25,177.85,171.50,176.25,172.50,11374468,"1,995,084,872.65",64834
353,21-Dec-2018,177.00,180.50,175.15,176.40,176.25,23742481,"4,229,437,224.65",153930
354,20-Dec-2018,173.00,177.30,171.75,173.90,176.40,15819006,"2,768,390,588.60",91578
355,19-Dec-2018,176.50,176.50,172.50,174.75,173.90,11540042,"2,012,157,930.40",66466
356,18-Dec-2018,174.00,177.60,173.10,173.95,174.75,18015933,"3,151,157,475.45",111145
357,17-Dec-2018,167.25,175.95,167.25,166.95,173.95,28526103,"4,952,303,673.10",158893
358,14-Dec-2018,166.00,168.40,164.85,166.85,166.95,10091732,"1,685,056,156.00",70024
359,13-Dec-2018,166.00,168.00,165.55,164.10,166.85,12235499,"2,041,875,870.10",92984
360,12-Dec-2018,159.50,167.10,158.00,158.10,164.10,22461175,"3,674,364,046.65",121969
361,11-Dec-2018,155.00,159.50,154.65,157.10,158.10,12094881,"1,903,118,965.55",77588
362,10-Dec-2018,159.90,160.50,156.50,162.40,157.10,13520495,"2,140,596,137.30",95871
363,07-Dec-2018,162.25,164.20,160.80,162.65,162.40,13545006,"2,201,399,505.00",93721
364,06-Dec-2018,168.50,168.70,161.60,169.20,162.65,15428019,"2,542,592,957.55",138289
365,05-Dec-2018,173.00,173.00,168.60,175.75,169.20,14960527,"2,552,820,507.95",104924
366,04-Dec-2018,177.95,178.75,175.30,175.45,175.75,11481923,"2,031,075,814.35",77401
367,03-Dec-2018,173.25,176.45,170.00,171.95,175.45,14068885,"2,451,369,931.20",88740

Describing the dataset in different ways

In [9]:
data.shape #showing the shape of the data

(368, 10)

In [11]:
#Checking the mean, count, standard deviation, min and max values of each column
data.describe()

,OPEN,HIGH,LOW,PREV. CLOSE,CLOSE,TOTAL TRADED QUANTITY,NO. OF TRADES
count,368.000000,368.000000,368.000000,368.000000,368.000000,3.680000e+02,368.000000
mean,152.890489,156.006386,149.430842,152.726902,152.509103,3.866013e+07,165734.432065
std,38.972475,39.270696,38.606442,38.886274,39.003689,2.723205e+07,90210.567646
min,66.500000,66.900000,63.500000,65.300000,65.300000,6.141180e+06,42618.000000
25%,126.500000,128.750000,122.162500,125.175000,124.425000,1.894944e+07,102597.750000
50%,166.600000,168.800000,163.100000,166.075000,165.975000,3.147517e+07,144671.500000
75%,178.350000,182.112500,175.187500,177.512500,177.512500,5.033121e+07,202223.250000
max,235.000000,239.350000,231.700000,236.250000,236.250000,1.844356e+08,720492.000000

In [13]:
#getting info about the data
data.info

<bound method DataFrame.info of             DATE SERIES   OPEN    HIGH     LOW   PREV. CLOSE    CLOSE  \
0    03-Jun-2020     EQ  100.00  101.45   97.40         96.50   98.75
1    01-Jun-2020     EQ   88.90   91.20   88.00         87.00   89.55
2    29-May-2020     EQ   85.55   87.50   84.65         87.00   87.00
3    28-May-2020     EQ   86.00   88.15   84.55         84.55   87.00
4    27-May-2020     EQ   84.10   86.00   84.00         83.10   84.55
5    26-May-2020     EQ   83.90   85.70   82.60         82.80   83.10
6    22-May-2020     EQ   83.40   83.90   82.00         84.10   82.80
7    21-May-2020     EQ   83.10   85.20   82.90         83.45   84.10
8    20-May-2020     EQ   81.25   84.40   80.70         81.80   83.45
9    19-May-2020     EQ   82.50   85.65   81.50         80.65   81.80
10   18-May-2020     EQ   84.50   84.50   79.60         84.35   80.65
11   15-May-2020     EQ   84.70   85.35   82.80         83.80   84.35
12   14-May-2020     EQ   83.95   85.30   82.55         87.20   83.80
13   13-May-2020     EQ   92.50   92.50   86.25         86.20   87.20
14   12-May-2020     EQ   85.95   87.70   83.50         86.10   86.20
15   11-May-2020     EQ   81.45   90.65   81.40         81.05   86.10
16   08-May-2020     EQ   84.50   84.95   80.55         82.50   81.05
17   07-May-2020     EQ   82.90   84.65   82.10         83.20   82.50
18   06-May-2020     EQ   81.55   83.95   80.35         80.90   83.20
19   05-May-2020     EQ   86.00   86.80   80.40         83.90   80.90
20   04-May-2020     EQ   87.00   87.20   81.50         93.25   83.90
21   30-Apr-2020     EQ   85.95   93.75   85.95         78.15   93.25
22   29-Apr-2020     EQ   77.45   79.30   76.55         76.95   78.15
23   28-Apr-2020     EQ   75.65   78.20   75.20         75.25   76.95
24   27-Apr-2020     EQ   75.90   76.20   74.80         74.20   75.25
25   24-Apr-2020     EQ   75.00   76.90   74.00         75.65   74.20
26   23-Apr-2020     EQ   76.75   78.65   75.40         75.90   75.65
27   22-Apr-2020     EQ   74.45   76.55   72.55         74.65   75.90
28   21-Apr-2020     EQ   78.00   78.00   74.00         80.45   74.65
29   20-Apr-2020     EQ   76.85   83.40   75.50         76.85   80.45
..           ...    ...     ...     ...     ...           ...     ...
338  14-Jan-2019     EQ  180.30  198.30  177.45        180.30  182.40
339  11-Jan-2019     EQ  186.55  187.75  179.40        185.75  180.30
340  10-Jan-2019     EQ  183.65  186.85  183.55        183.05  185.75
341  09-Jan-2019     EQ  181.50  183.60  180.20        179.95  183.05
342  08-Jan-2019     EQ  176.10  180.50  176.10        175.35  179.95
343  07-Jan-2019     EQ  173.20  178.20  173.20        170.95  175.35
344  04-Jan-2019     EQ  169.00  171.95  168.50        166.05  170.95
345  03-Jan-2019     EQ  169.00  170.15  165.10        168.55  166.05
346  02-Jan-2019     EQ  170.60  171.75  168.00        173.45  168.55
347  01-Jan-2019     EQ  173.50  174.20  171.30        172.70  173.45
348  31-Dec-2018     EQ  172.45  173.90  171.75        170.85  172.70
349  28-Dec-2018     EQ  169.40  172.20  169.15        168.25  170.85
350  27-Dec-2018     EQ  172.75  173.40  167.70        170.90  168.25
351  26-Dec-2018     EQ  171.45  172.20  167.60        172.50  170.90
352  24-Dec-2018     EQ  176.25  177.85  171.50        176.25  172.50
353  21-Dec-2018     EQ  177.00  180.50  175.15        176.40  176.25
354  20-Dec-2018     EQ  173.00  177.30  171.75        173.90  176.40
355  19-Dec-2018     EQ  176.50  176.50  172.50        174.75  173.90
356  18-Dec-2018     EQ  174.00  177.60  173.10        173.95  174.75
357  17-Dec-2018     EQ  167.25  175.95  167.25        166.95  173.95
358  14-Dec-2018     EQ  166.00  168.40  164.85        166.85  166.95
359  13-Dec-2018     EQ  166.00  168.00  165.55        164.10  166.85
360  12-Dec-2018     EQ  159.50  167.10  158.00        158.10  164.10
361  11-Dec-2018     EQ  155.00  159.50  154.65        157.10  158.10
362  10-Dec-2018     EQ  159.90  160.50  156.50        162.40  157.10
363  07-Dec-2018     EQ  162.25  164.20  160.80        162.65  162.40
364  06-Dec-2018     EQ  168.50  168.70  161.60        169.20  162.65
365  05-Dec-2018     EQ  173.00  173.00  168.60        175.75  169.20
366  04-Dec-2018     EQ  177.95  178.75  175.30        175.45  175.75
367  03-Dec-2018     EQ  173.25  176.45  170.00        171.95  175.45

     TOTAL TRADED QUANTITY           TURNOVER  NO. OF TRADES
0                 90600115   9,073,798,058.20         296653
1                 71081216   6,399,189,823.50         207071
2                 80819025   6,937,284,941.50         210894
3                 96183461   8,317,754,409.30         254053
4                 57958863   4,923,419,055.20         144270
5                 38018351   3,197,222,250.60         116618
6                 29252936   2,422,831,924.30          96301
7                 37290910   3,142,196,365.85         119854
8                 36351616   3,015,914,660.45         116445
9                 65379359   5,469,427,810.40         194462
10                44221575   3,588,181,738.75         163410
11                38594210   3,238,366,014.30         124113
12                46341703   3,896,726,738.70         173963
13                68086246   6,036,002,630.40         237994
14                77552355   6,593,767,114.50         245351
15               152592033  13,267,842,790.60         470511
16                35363226   2,916,175,375.35         135944
17                31160671   2,595,015,270.60         119183
18                53739428   4,435,743,139.40         166733
19                57123018   4,816,372,491.95         194041
20                91167307   7,666,846,446.55         327945
21               170645234  15,233,902,188.60         519684
22                40785025   3,184,101,597.95         133880
23                34825466   2,675,737,156.65         107365
24                27835405   2,098,869,538.60          93555
25                40054235   3,024,343,540.85         129250
26                50372620   3,875,896,447.15         161989
27                56529909   4,202,665,230.00         183754
28                58249560   4,396,212,525.25         223568
29               125427754  10,152,471,072.75         400016
..                     ...                ...            ...
338               18935120   3,422,007,613.90          94255
339               25902974   4,727,945,471.15         122548
340               16961888   3,150,521,337.85          96659
341               17468948   3,180,237,350.20         114177
342               20128985   3,603,338,781.30         116893
343               21438351   3,778,953,045.30         136086
344               17650435   3,008,777,564.85         103949
345                9321842   1,564,267,952.55          71994
346               13410104   2,277,669,120.50          77641
347                6715543   1,159,866,971.20          42618
348                8511388   1,470,736,017.50          53654
349                8669584   1,483,786,775.25          52303
350               15231581   2,587,331,015.45          78643
351               12044191   2,047,301,453.05          73360
352               11374468   1,995,084,872.65          64834
353               23742481   4,229,437,224.65         153930
354               15819006   2,768,390,588.60          91578
355               11540042   2,012,157,930.40          66466
356               18015933   3,151,157,475.45         111145
357               28526103   4,952,303,673.10         158893
358               10091732   1,685,056,156.00          70024
359               12235499   2,041,875,870.10          92984
360               22461175   3,674,364,046.65         121969
361               12094881   1,903,118,965.55          77588
362               13520495   2,140,596,137.30          95871
363               13545006   2,201,399,505.00          93721
364               15428019   2,542,592,957.55         138289
365               14960527   2,552,820,507.95         104924
366               11481923   2,031,075,814.35          77401
367               14068885   2,451,369,931.20          88740

[368 rows x 10 columns]>

# Value at the head of the data set

In [15]:
#checking the top 10 rows of the dataset
data.head(10)

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,CLOSE,TOTAL TRADED QUANTITY,TURNOVER,NO. OF TRADES
0,03-Jun-2020,EQ,100.00,101.45,97.40,96.50,98.75,90600115,"9,073,798,058.20",296653
1,01-Jun-2020,EQ,88.90,91.20,88.00,87.00,89.55,71081216,"6,399,189,823.50",207071
2,29-May-2020,EQ,85.55,87.50,84.65,87.00,87.00,80819025,"6,937,284,941.50",210894
3,28-May-2020,EQ,86.00,88.15,84.55,84.55,87.00,96183461,"8,317,754,409.30",254053
4,27-May-2020,EQ,84.10,86.00,84.00,83.10,84.55,57958863,"4,923,419,055.20",144270
5,26-May-2020,EQ,83.90,85.70,82.60,82.80,83.10,38018351,"3,197,222,250.60",116618
6,22-May-2020,EQ,83.40,83.90,82.00,84.10,82.80,29252936,"2,422,831,924.30",96301
7,21-May-2020,EQ,83.10,85.20,82.90,83.45,84.10,37290910,"3,142,196,365.85",119854
8,20-May-2020,EQ,81.25,84.40,80.70,81.80,83.45,36351616,"3,015,914,660.45",116445
9,19-May-2020,EQ,82.50,85.65,81.50,80.65,81.80,65379359,"5,469,427,810.40",194462

# Value at bottom of the dataset

In [28]:
#checking the bottom 10 rows of the dataset
data.tail(10)

,DATE,OPEN,HIGH,LOW,PREV. CLOSE,CLOSE,TOTAL TRADED QUANTITY,TURNOVER,NO. OF TRADES
358,14-Dec-2018,166.00,168.40,164.85,166.85,166.95,10091732,"1,685,056,156.00",70024
359,13-Dec-2018,166.00,168.00,165.55,164.10,166.85,12235499,"2,041,875,870.10",92984
360,12-Dec-2018,159.50,167.10,158.00,158.10,164.10,22461175,"3,674,364,046.65",121969
361,11-Dec-2018,155.00,159.50,154.65,157.10,158.10,12094881,"1,903,118,965.55",77588
362,10-Dec-2018,159.90,160.50,156.50,162.40,157.10,13520495,"2,140,596,137.30",95871
363,07-Dec-2018,162.25,164.20,160.80,162.65,162.40,13545006,"2,201,399,505.00",93721
364,06-Dec-2018,168.50,168.70,161.60,169.20,162.65,15428019,"2,542,592,957.55",138289
365,05-Dec-2018,173.00,173.00,168.60,175.75,169.20,14960527,"2,552,820,507.95",104924
366,04-Dec-2018,177.95,178.75,175.30,175.45,175.75,11481923,"2,031,075,814.35",77401
367,03-Dec-2018,173.25,176.45,170.00,171.95,175.45,14068885,"2,451,369,931.20",88740

# Name of the all the attributes of the dataset

In [20]:
data.columns

Index(['DATE', 'SERIES', 'OPEN ', 'HIGH ', 'LOW ', 'PREV. CLOSE ', 'CLOSE',
       'TOTAL TRADED QUANTITY', 'TURNOVER', 'NO. OF TRADES'],
      dtype='object')

# Datatypes of each attribute of the dataset

In [22]:
data.dtypes

DATE                      object
SERIES                    object
OPEN                     float64
HIGH                     float64
LOW                      float64
PREV. CLOSE              float64
CLOSE                    float64
TOTAL TRADED QUANTITY      int64
TURNOVER                  object
NO. OF TRADES              int64
dtype: object

# Removing non significant columns

Printing the total unique value for each column

In [24]:
for i in data.columns:
    print(i,len(data[i].unique()))

DATE 368
SERIES 1
OPEN  317
HIGH  332
LOW  329
PREV. CLOSE  337
CLOSE 337
TOTAL TRADED QUANTITY 368
TURNOVER 368
NO. OF TRADES 367

# Dropping unwanted attributes from the dataset

In [ ]:
#since 'SERIES' is not a attribute needed for the purpose, it should be removed.
data.drop('SERIES',axis=1,inplace=True)

# Checking missing values for each columns

In [31]:
data.isnull().sum()

DATE                     0
OPEN                     0
HIGH                     0
LOW                      0
PREV. CLOSE              0
CLOSE                    0
TOTAL TRADED QUANTITY    0
TURNOVER                 0
NO. OF TRADES            0
dtype: int64

# There are no null columns

In [33]:
data.columns

Index(['DATE', 'OPEN ', 'HIGH ', 'LOW ', 'PREV. CLOSE ', 'CLOSE',
       'TOTAL TRADED QUANTITY', 'TURNOVER', 'NO. OF TRADES'],
      dtype='object')

In [39]:
data.dtypes

DATE                      object
OPEN                     float64
HIGH                     float64
LOW                      float64
PREV. CLOSE              float64
CLOSE                    float64
TOTAL TRADED QUANTITY      int64
TURNOVER                  object
NO. OF TRADES              int64
dtype: object

# Formatting Data – making data types compaitable with other data types

'TOTAL TRADED QUANTITY','TURNOVER' and 'NO. OF TRADE' are the only column wih different data types

In [43]:
#coverting 'TOTAL TRADED QUANTITY' and 'NO. OF TRADES' to float.
data['TOTAL TRADED QUANTITY'] = data['TOTAL TRADED QUANTITY'].astype(float)
data['NO. OF TRADES'] = data['NO. OF TRADES'].astype(float)

In [46]:
# Checking if the values changed correctly or not
data

,DATE,OPEN,HIGH,LOW,PREV. CLOSE,CLOSE,TOTAL TRADED QUANTITY,TURNOVER,NO. OF TRADES
0,03-Jun-2020,100.00,101.45,97.40,96.50,98.75,90600115.0,"9,073,798,058.20",296653.0
1,01-Jun-2020,88.90,91.20,88.00,87.00,89.55,71081216.0,"6,399,189,823.50",207071.0
2,29-May-2020,85.55,87.50,84.65,87.00,87.00,80819025.0,"6,937,284,941.50",210894.0
3,28-May-2020,86.00,88.15,84.55,84.55,87.00,96183461.0,"8,317,754,409.30",254053.0
4,27-May-2020,84.10,86.00,84.00,83.10,84.55,57958863.0,"4,923,419,055.20",144270.0
5,26-May-2020,83.90,85.70,82.60,82.80,83.10,38018351.0,"3,197,222,250.60",116618.0
6,22-May-2020,83.40,83.90,82.00,84.10,82.80,29252936.0,"2,422,831,924.30",96301.0
7,21-May-2020,83.10,85.20,82.90,83.45,84.10,37290910.0,"3,142,196,365.85",119854.0
8,20-May-2020,81.25,84.40,80.70,81.80,83.45,36351616.0,"3,015,914,660.45",116445.0
9,19-May-2020,82.50,85.65,81.50,80.65,81.80,65379359.0,"5,469,427,810.40",194462.0
10,18-May-2020,84.50,84.50,79.60,84.35,80.65,44221575.0,"3,588,181,738.75",163410.0
11,15-May-2020,84.70,85.35,82.80,83.80,84.35,38594210.0,"3,238,366,014.30",124113.0
12,14-May-2020,83.95,85.30,82.55,87.20,83.80,46341703.0,"3,896,726,738.70",173963.0
13,13-May-2020,92.50,92.50,86.25,86.20,87.20,68086246.0,"6,036,002,630.40",237994.0
14,12-May-2020,85.95,87.70,83.50,86.10,86.20,77552355.0,"6,593,767,114.50",245351.0
15,11-May-2020,81.45,90.65,81.40,81.05,86.10,152592033.0,"13,267,842,790.60",470511.0
16,08-May-2020,84.50,84.95,80.55,82.50,81.05,35363226.0,"2,916,175,375.35",135944.0
17,07-May-2020,82.90,84.65,82.10,83.20,82.50,31160671.0,"2,595,015,270.60",119183.0
18,06-May-2020,81.55,83.95,80.35,80.90,83.20,53739428.0,"4,435,743,139.40",166733.0
19,05-May-2020,86.00,86.80,80.40,83.90,80.90,57123018.0,"4,816,372,491.95",194041.0
20,04-May-2020,87.00,87.20,81.50,93.25,83.90,91167307.0,"7,666,846,446.55",327945.0
21,30-Apr-2020,85.95,93.75,85.95,78.15,93.25,170645234.0,"15,233,902,188.60",519684.0
22,29-Apr-2020,77.45,79.30,76.55,76.95,78.15,40785025.0,"3,184,101,597.95",133880.0
23,28-Apr-2020,75.65,78.20,75.20,75.25,76.95,34825466.0,"2,675,737,156.65",107365.0
24,27-Apr-2020,75.90,76.20,74.80,74.20,75.25,27835405.0,"2,098,869,538.60",93555.0
25,24-Apr-2020,75.00,76.90,74.00,75.65,74.20,40054235.0,"3,024,343,540.85",129250.0
26,23-Apr-2020,76.75,78.65,75.40,75.90,75.65,50372620.0,"3,875,896,447.15",161989.0
27,22-Apr-2020,74.45,76.55,72.55,74.65,75.90,56529909.0,"4,202,665,230.00",183754.0
28,21-Apr-2020,78.00,78.00,74.00,80.45,74.65,58249560.0,"4,396,212,525.25",223568.0
29,20-Apr-2020,76.85,83.40,75.50,76.85,80.45,125427754.0,"10,152,471,072.75",400016.0
...,...,...,...,...,...,...,...,...,...
338,14-Jan-2019,180.30,198.30,177.45,180.30,182.40,18935120.0,"3,422,007,613.90",94255.0
339,11-Jan-2019,186.55,187.75,179.40,185.75,180.30,25902974.0,"4,727,945,471.15",122548.0
340,10-Jan-2019,183.65,186.85,183.55,183.05,185.75,16961888.0,"3,150,521,337.85",96659.0
341,09-Jan-2019,181.50,183.60,180.20,179.95,183.05,17468948.0,"3,180,237,350.20",114177.0
342,08-Jan-2019,176.10,180.50,176.10,175.35,179.95,20128985.0,"3,603,338,781.30",116893.0
343,07-Jan-2019,173.20,178.20,173.20,170.95,175.35,21438351.0,"3,778,953,045.30",136086.0
344,04-Jan-2019,169.00,171.95,168.50,166.05,170.95,17650435.0,"3,008,777,564.85",103949.0
345,03-Jan-2019,169.00,170.15,165.10,168.55,166.05,9321842.0,"1,564,267,952.55",71994.0
346,02-Jan-2019,170.60,171.75,168.00,173.45,168.55,13410104.0,"2,277,669,120.50",77641.0
347,01-Jan-2019,173.50,174.20,171.30,172.70,173.45,6715543.0,"1,159,866,971.20",42618.0
348,31-Dec-2018,172.45,173.90,171.75,170.85,172.70,8511388.0,"1,470,736,017.50",53654.0
349,28-Dec-2018,169.40,172.20,169.15,168.25,170.85,8669584.0,"1,483,786,775.25",52303.0
350,27-Dec-2018,172.75,173.40,167.70,170.90,168.25,15231581.0,"2,587,331,015.45",78643.0
351,26-Dec-2018,171.45,172.20,167.60,172.50,170.90,12044191.0,"2,047,301,453.05",73360.0
352,24-Dec-2018,176.25,177.85,171.50,176.25,172.50,11374468.0,"1,995,084,872.65",64834.0
353,21-Dec-2018,177.00,180.50,175.15,176.40,176.25,23742481.0,"4,229,437,224.65",153930.0
354,20-Dec-2018,173.00,177.30,171.75,173.90,176.40,15819006.0,"2,768,390,588.60",91578.0
355,19-Dec-2018,176.50,176.50,172.50,174.75,173.90,11540042.0,"2,012,157,930.40",66466.0
356,18-Dec-2018,174.00,177.60,173.10,173.95,174.75,18015933.0,"3,151,157,475.45",111145.0
357,17-Dec-2018,167.25,175.95,167.25,166.95,173.95,28526103.0,"4,952,303,673.10",158893.0
358,14-Dec-2018,166.00,168.40,164.85,166.85,166.95,10091732.0,"1,685,056,156.00",70024.0
359,13-Dec-2018,166.00,168.00,165.55,164.10,166.85,12235499.0,"2,041,875,870.10",92984.0
360,12-Dec-2018,159.50,167.10,158.00,158.10,164.10,22461175.0,"3,674,364,046.65",121969.0
361,11-Dec-2018,155.00,159.50,154.65,157.10,158.10,12094881.0,"1,903,118,965.55",77588.0
362,10-Dec-2018,159.90,160.50,156.50,162.40,157.10,13520495.0,"2,140,596,137.30",95871.0
363,07-Dec-2018,162.25,164.20,160.80,162.65,162.40,13545006.0,"2,201,399,505.00",93721.0
364,06-Dec-2018,168.50,168.70,161.60,169.20,162.65,15428019.0,"2,542,592,957.55",138289.0
365,05-Dec-2018,173.00,173.00,168.60,175.75,169.20,14960527.0,"2,552,820,507.95",104924.0
366,04-Dec-2018,177.95,178.75,175.30,175.45,175.75,11481923.0,"2,031,075,814.35",77401.0
367,03-Dec-2018,173.25,176.45,170.00,171.95,175.45,14068885.0,"2,451,369,931.20",88740.0

In [83]:
#first coverting 'TURNOVER' to string datatype
data["TURNOVER"] = data["TURNOVER"].astype(str)

In [88]:
#then converting 'TURNOVER' form string to float datatype
data["TURNOVER"] = data["TURNOVER"].astype(float)

In [90]:
data

,DATE,OPEN,HIGH,LOW,PREV. CLOSE,CLOSE,TOTAL TRADED QUANTITY,TURNOVER,NO. OF TRADES
0,03-Jun-2020,100.00,101.45,97.40,96.50,98.75,90600115.0,9.073798e+09,296653.0
1,01-Jun-2020,88.90,91.20,88.00,87.00,89.55,71081216.0,6.399190e+09,207071.0
2,29-May-2020,85.55,87.50,84.65,87.00,87.00,80819025.0,6.937285e+09,210894.0
3,28-May-2020,86.00,88.15,84.55,84.55,87.00,96183461.0,8.317754e+09,254053.0
4,27-May-2020,84.10,86.00,84.00,83.10,84.55,57958863.0,4.923419e+09,144270.0
5,26-May-2020,83.90,85.70,82.60,82.80,83.10,38018351.0,3.197222e+09,116618.0
6,22-May-2020,83.40,83.90,82.00,84.10,82.80,29252936.0,2.422832e+09,96301.0
7,21-May-2020,83.10,85.20,82.90,83.45,84.10,37290910.0,3.142196e+09,119854.0
8,20-May-2020,81.25,84.40,80.70,81.80,83.45,36351616.0,3.015915e+09,116445.0
9,19-May-2020,82.50,85.65,81.50,80.65,81.80,65379359.0,5.469428e+09,194462.0
10,18-May-2020,84.50,84.50,79.60,84.35,80.65,44221575.0,3.588182e+09,163410.0
11,15-May-2020,84.70,85.35,82.80,83.80,84.35,38594210.0,3.238366e+09,124113.0
12,14-May-2020,83.95,85.30,82.55,87.20,83.80,46341703.0,3.896727e+09,173963.0
13,13-May-2020,92.50,92.50,86.25,86.20,87.20,68086246.0,6.036003e+09,237994.0
14,12-May-2020,85.95,87.70,83.50,86.10,86.20,77552355.0,6.593767e+09,245351.0
15,11-May-2020,81.45,90.65,81.40,81.05,86.10,152592033.0,1.326784e+10,470511.0
16,08-May-2020,84.50,84.95,80.55,82.50,81.05,35363226.0,2.916175e+09,135944.0
17,07-May-2020,82.90,84.65,82.10,83.20,82.50,31160671.0,2.595015e+09,119183.0
18,06-May-2020,81.55,83.95,80.35,80.90,83.20,53739428.0,4.435743e+09,166733.0
19,05-May-2020,86.00,86.80,80.40,83.90,80.90,57123018.0,4.816372e+09,194041.0
20,04-May-2020,87.00,87.20,81.50,93.25,83.90,91167307.0,7.666846e+09,327945.0
21,30-Apr-2020,85.95,93.75,85.95,78.15,93.25,170645234.0,1.523390e+10,519684.0
22,29-Apr-2020,77.45,79.30,76.55,76.95,78.15,40785025.0,3.184102e+09,133880.0
23,28-Apr-2020,75.65,78.20,75.20,75.25,76.95,34825466.0,2.675737e+09,107365.0
24,27-Apr-2020,75.90,76.20,74.80,74.20,75.25,27835405.0,2.098870e+09,93555.0
25,24-Apr-2020,75.00,76.90,74.00,75.65,74.20,40054235.0,3.024344e+09,129250.0
26,23-Apr-2020,76.75,78.65,75.40,75.90,75.65,50372620.0,3.875896e+09,161989.0
27,22-Apr-2020,74.45,76.55,72.55,74.65,75.90,56529909.0,4.202665e+09,183754.0
28,21-Apr-2020,78.00,78.00,74.00,80.45,74.65,58249560.0,4.396213e+09,223568.0
29,20-Apr-2020,76.85,83.40,75.50,76.85,80.45,125427754.0,1.015247e+10,400016.0
...,...,...,...,...,...,...,...,...,...
338,14-Jan-2019,180.30,198.30,177.45,180.30,182.40,18935120.0,3.422008e+09,94255.0
339,11-Jan-2019,186.55,187.75,179.40,185.75,180.30,25902974.0,4.727945e+09,122548.0
340,10-Jan-2019,183.65,186.85,183.55,183.05,185.75,16961888.0,3.150521e+09,96659.0
341,09-Jan-2019,181.50,183.60,180.20,179.95,183.05,17468948.0,3.180237e+09,114177.0
342,08-Jan-2019,176.10,180.50,176.10,175.35,179.95,20128985.0,3.603339e+09,116893.0
343,07-Jan-2019,173.20,178.20,173.20,170.95,175.35,21438351.0,3.778953e+09,136086.0
344,04-Jan-2019,169.00,171.95,168.50,166.05,170.95,17650435.0,3.008778e+09,103949.0
345,03-Jan-2019,169.00,170.15,165.10,168.55,166.05,9321842.0,1.564268e+09,71994.0
346,02-Jan-2019,170.60,171.75,168.00,173.45,168.55,13410104.0,2.277669e+09,77641.0
347,01-Jan-2019,173.50,174.20,171.30,172.70,173.45,6715543.0,1.159867e+09,42618.0
348,31-Dec-2018,172.45,173.90,171.75,170.85,172.70,8511388.0,1.470736e+09,53654.0
349,28-Dec-2018,169.40,172.20,169.15,168.25,170.85,8669584.0,1.483787e+09,52303.0
350,27-Dec-2018,172.75,173.40,167.70,170.90,168.25,15231581.0,2.587331e+09,78643.0
351,26-Dec-2018,171.45,172.20,167.60,172.50,170.90,12044191.0,2.047301e+09,73360.0
352,24-Dec-2018,176.25,177.85,171.50,176.25,172.50,11374468.0,1.995085e+09,64834.0
353,21-Dec-2018,177.00,180.50,175.15,176.40,176.25,23742481.0,4.229437e+09,153930.0
354,20-Dec-2018,173.00,177.30,171.75,173.90,176.40,15819006.0,2.768391e+09,91578.0
355,19-Dec-2018,176.50,176.50,172.50,174.75,173.90,11540042.0,2.012158e+09,66466.0
356,18-Dec-2018,174.00,177.60,173.10,173.95,174.75,18015933.0,3.151157e+09,111145.0
357,17-Dec-2018,167.25,175.95,167.25,166.95,173.95,28526103.0,4.952304e+09,158893.0
358,14-Dec-2018,166.00,168.40,164.85,166.85,166.95,10091732.0,1.685056e+09,70024.0
359,13-Dec-2018,166.00,168.00,165.55,164.10,166.85,12235499.0,2.041876e+09,92984.0
360,12-Dec-2018,159.50,167.10,158.00,158.10,164.10,22461175.0,3.674364e+09,121969.0
361,11-Dec-2018,155.00,159.50,154.65,157.10,158.10,12094881.0,1.903119e+09,77588.0
362,10-Dec-2018,159.90,160.50,156.50,162.40,157.10,13520495.0,2.140596e+09,95871.0
363,07-Dec-2018,162.25,164.20,160.80,162.65,162.40,13545006.0,2.201400e+09,93721.0
364,06-Dec-2018,168.50,168.70,161.60,169.20,162.65,15428019.0,2.542593e+09,138289.0
365,05-Dec-2018,173.00,173.00,168.60,175.75,169.20,14960527.0,2.552821e+09,104924.0
366,04-Dec-2018,177.95,178.75,175.30,175.45,175.75,11481923.0,2.031076e+09,77401.0
367,03-Dec-2018,173.25,176.45,170.00,171.95,175.45,14068885.0,2.451370e+09,88740.0

# Finally checking the datatype of all the column -> float64

In [92]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368 entries, 0 to 367
Data columns (total 9 columns):
DATE                     368 non-null object
OPEN                     368 non-null float64
HIGH                     368 non-null float64
LOW                      368 non-null float64
PREV. CLOSE              368 non-null float64
CLOSE                    368 non-null float64
TOTAL TRADED QUANTITY    368 non-null float64
TURNOVER                 368 non-null float64
NO. OF TRADES            368 non-null float64
dtypes: float64(8), object(1)
memory usage: 26.0+ KB

In [93]:
#checking the new shape of the processed data
data.shape

(368, 9)